name: Backend Tests

on:
  push:
    branches: [main,'feature/test-branch-protection']
  pull_request:  # ✨ Nouveau !
    branches: [main]
  workflow_call:  # ✨ Nouveau !

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO : Setup Python 3.11 avec cache pip
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # TODO : Installez UV avec pip
      - name: Install UV
        run: |
          pip install uv

      # TODO : Installez les dépendances (cd backend && uv sync)
      - name: Install dependencies
        run: |
          cd backend && uv sync

      # TODO : Lancez les tests
      - name: Run tests
        run: |
          cd backend && uv run pytest -v --cov